project_id = "wwjngmmnlacuiospztrm"

[functions.translate-text]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false

[functions.transliterate-text]
verify_jwt = false

[functions.send-resolution-email]
verify_jwt = false
